FROM php:8.3-cli

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
git \
unzip \
libzip-dev \
libpng-dev \
libjpeg62-turbo-dev \
libfreetype6-dev \
libonig-dev \
ffmpeg \
&& docker-php-ext-install \
pdo_mysql \
mbstring \
exif \
pcntl \
bcmath \
gd \
zip \
&& rm -rf /var/lib/apt/lists/*


COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install \
--no-dev \
--no-interaction \
--prefer-dist \
--optimize-autoloader


RUN mkdir -p storage/framework/cache \
storage/framework/sessions \
storage/framework/views \
storage/logs \
bootstrap/cache


RUN chmod -R 775 storage bootstrap/cache


CMD ["php", "artisan", "queue:work", "--tries=3", "--timeout=900"]